export const ACTION_PROJECT_FETCH_BY_ID = "PROJECT:FETCHING_BY_ID";
export const ACTION_PROJECT_FETCH_BY_PROJECTID = "PROJECT:FETCHING_BY_USERID";
export const ACTION_PROJECT_SET_BY_PROJECTID = "PROJECT:SET_BY_USERID";
export const ACTION_PROJECT_SET_BY_ID = "PROJECT:SET_BY_ID";
export const ACTION_PROJECT_ERROR = "PROJECT:ERROR";